version: '3'
services: 
  app: 
    container_name: viacep-app
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
     - 9002:80
    restart: unless-stopped
    depends_on:
     - db
    networks:
     - app-network

  db:
    image: mysql
    container_name: viacep-db
    restart: always
    ports:
      - 3338:3338
    volumes:
      - ./.docker/database-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viacep
      MYSQL_USER: viacep
      MYSQL_PASSWORD: viacep
      MYSQL_TCP_PORT: 3338
    networks:
     - app-network

networks:
  app-network:
    driver: bridge